config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :books
    end
  end
  devise_for :users
  root "catageroys#index"
  resources :products
  resources :catageroys
  resources :carts
  get 'carts/sub/:id', to: 'carts#sub', as: 'sub'
  get 'products/cart/:id', to: 'products#cart', as: 'addcart'
  # get 'carts/show', to: 'cart#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :admin do
    resources :products
    resources :catageroys
  end
end

app/models/catageroy.rb
class Catageroy < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/catageroys_controller.rb
class Admin::CatageroysController < Admin::BaseController
  before_action :set_catageroy, only: %i[ show edit update destroy ]
  before_action :check, only: %i[ index new show edit update destroy ]
  # GET /catageroys or /catageroys.json
  def index
    @catageroys = Catageroy.all
    @product = Product.all
    @order = Order.all
  end

  # GET /catageroys/1 or /catageroys/1.json
  def show
  end

  # GET /catageroys/new
  def new
    @catageroy = Catageroy.new
  end

  # GET /catageroys/1/edit
  def edit
    
  end

  # POST /catageroys or /catageroys.json
  def create
    @catageroy = Catageroy.new(catageroy_params)

    respond_to do |format|
      if @catageroy.save
        format.html { redirect_to new_admin_catageroy_path, notice: "Catageroys was successfully created." }
        format.json { render :show, status: :created, location: @catageroy }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @catageroy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catageroys/1 or /catageroys/1.json
  def update
     @catageroy.update(catageroy_params)
    respond_to do |format|
      if @catageroy.update(catageroy_params)
        format.html { redirect_to new_admin_catageroy_path, notice: "Catageroy was successfully updated." }
        format.json { render :show, status: :ok, location: @catageroy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @catageroy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catageroys/1 or /catageroys/1.json
  def destroy
    @catageroy.destroy

    respond_to do |format|
      format.html { redirect_to catageroys_url, notice: "Catageroy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catageroy
      @catageroy = Catageroy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def catageroy_params
      params.require(:catageroy).permit(:name)
    end


    def check
      if current_user && current_user.role == "admin"
        puts "Admin :"
        puts current_user.role
        

      else
        puts "Admin not Exist"
        redirect_to new_user_session_path
      end
    end
end

app/controllers/catageroys_controller.rb
class CatageroysController < ApplicationController
  before_action :set_catageroy, only: %i[ show  ]

  # GET /catageroys or /catageroys.json
  def index
    @catageroys = Catageroy.all
    @product = Product.all

    if params[:commit]=="name"
      @product =  Product.where("title LIKE ?", ["%#{params[:name]}%"])
    end
    if params[:commit]=="Price"
      @product =  Product.where("price LIKE ?", ["%#{params[:name]}%"])
    end
  end

  # GET /catageroys/1 or /catageroys/1.json
  def show
  end

  # GET /catageroys/new
  # def new
  #   @catageroy = Catageroy.new
  # end

  # GET /catageroys/1/edit
  # def edit
  # end

  # POST /catageroys or /catageroys.json
  # def create
  #   @catageroy = Catageroy.new(catageroy_params)

  #   respond_to do |format|
  #     if @catageroy.save
  #       format.html { redirect_to catageroys_path, notice: "Catageroy was successfully created." }
  #       format.json { render :show, status: :created, location: @catageroy }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @catageroy.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /catageroys/1 or /catageroys/1.json
  # def update
  #   respond_to do |format|
  #     if @catageroy.update(catageroy_params)
  #       format.html { redirect_to catageroy_url(@catageroy), notice: "Catageroy was successfully updated." }
  #       format.json { render :show, status: :ok, location: @catageroy }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @catageroy.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /catageroys/1 or /catageroys/1.json
  # def destroy
  #   @catageroy.destroy

  #   respond_to do |format|
  #     format.html { redirect_to catageroys_url, notice: "Catageroy was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catageroy
      @catageroy = Catageroy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def catageroy_params
      params.require(:catageroy).permit(:name)
    end
end

app/helpers/catageroys_helper.rb
module CatageroysHelper
end

app/views/admin/catageroys/_catageroy.html.erb
<div id="<%= dom_id catageroy %>" style=" justify-content:between">
    <h5 style="margin-top:10px">
      <a href="/catageroys/<%= catageroy.id %>" style="text-decoration: none;"> <b style="color:yellow">|</b>
        <%= catageroy.name %>
      </a>
    </h5>
</div>

app/views/admin/catageroys/_form.html.erb
<%= form_for catageroy, url:url do |form| %>
  <% if catageroy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(catageroy.errors.count, "error") %> prohibited this catageroy from being saved:</h2>

      <ul>
        <% catageroy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/catageroys/edit.html.erb
<h1>Editing catageroy</h1>

<%= render "form", catageroy: @catageroy, url: admin_catageroy_path(@catageroy) %>

<br>

<div>
  
  <%= link_to "Back to catageroys", new_admin_catageroy_path %>
  
</div>

app/views/admin/catageroys/index.html.erb
  <style>
    tr {
      border: 2px solid;
    }

    table,
    tr,
    td {
      padding-right: 20px !important;
    }
  </style>



  <div style="display:flex;justify-content:space-between; background-color:black">
    <div>
      <a href="/admin/catageroys" style="text-decoration: none;color:white">
        <h1 style="color:white">MastShop</h1>
        <p style="margin-top:-15px;margin-left:10px; font-size:14px;color:pink">Comfortable Life Style</p>
      </a>
    </div>



    <!-- # <div id="catageroys" style="display:flex; flex-direction:row; ">
          #      <% @catageroys.each do |catageroy| %>
          #           <%#= render catageroy %>
          #      <% end %>
          # </div> -->

    <div>
      <div style="display:flex">


        <div>
          <% if current_user%>
          <%= current_user.email %><br>
          <%= link_to "Edit", edit_user_registration_path() %> |
          <%= link_to "LogOut", destroy_user_session_path, data: { turbo_method: :delete } %>

          <%else%>
          <%= link_to "LogIn", new_user_session_path() %> |
          <%= link_to "Signup", new_user_registration_path() %>
          <%end%>
        </div>
        <a href="/carts" style="color:white; font-size:15px;margin-right:50px;margin-left:50px">
          <div class="position-relative d-flex justify-content-center align-items-start">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" width="30" height="40" viewBox="0 0 24 24"
              stroke-width="1.5" stroke="white" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round"
                d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
            </svg>
            <div class="position-absolute bottom-0 mb-1">
              <%= Cart.count%>
            </div>
          </div>
          <!-- <a href="/catageroys/new/" style="text-decoration: none;margin-right:20px; color:gray">
            <h7> <b>+</b> Catageroy</h7>
          </a> -->
        </a>
      </div>


    </div>

  </div>



  <div>
    <div>
      <a href="/admin/catageroys/new">Add New Catagaries</a>
    </div>
    <div>
       <%= link_to "New product", new_admin_product_path %>
    </div>
  </div>

  <br><br><br>







  <div style="display:flex; justify-content: space-around">
      <div>
          <table>
            <tr>
              <td><b>Image</td>
              <td><b>Title</td>
              <td><b>Quantity</td>
              <td><b>Price</td>
              <td><b>Catagaries</td>
              <td><b>Action</td>
            </tr>
            <% @product.each do |prod|%>
            <% @cat = Catageroy.find(prod.Catageroy_id)%>
            <tr>
              <td><%= image_tag prod.f_image, width:"70px", height:"70px"%></td>
              <td><%= prod.title%></td>
              <td><%= prod.qty%></td>
              <td><%= prod.price%></td>
              <td><%= @cat.name %></td>
              <td>  <%= link_to 'Edit', edit_admin_product_path(prod.id)%><br><%= link_to 'delete', admin_product_path(prod.id), data: { turbo_method: :delete } %> </td>
            </tr>
            <%end%>
          </table>
      </div>


      <div>
          <table>
          <tr>
            <td><b>Image</td>
            <td><b>Usere</td>
            <td><b>Quantity</td>
            <td><b>Price</td>
            <td><b>Catagaries</td>
            <td><b>Action</td>
          </tr>
          <% @order.each do |prod|%>
          <% @product = Product.find(prod.pid)%>
          <tr>
            <td><%= image_tag @product.f_image, width:"70px", height:"70px" if @product.f_image.attached?%></td>
            <td><%= prod.user%></td>
            <td><%= prod.quantity%></td>
            <td><%= prod.price%></td>
            <td><%= prod.id %></td>
            <td> <%= link_to 'delete', cart_path(prod.id), data: { turbo_method: :delete } %> </td>
          </tr>
          <%end%>
        </table>

      </div>
  </div>






















<%
=begin
%>

<div style="display:flex; flex-wrap:wrap; justify-content:center;">
  <% @product.each do |prod|%>
  <a href="/products/<%= prod.id%>" style="text-decoration: none;">
    <div
      style="display:flex; flex-direction:column; width:300px; height:300px; background-color:white; margin:30px; border-radius: 10px;  ">
      <div class="">
        <%= image_tag prod.f_image, height:'240px', width:'300px' ,border_radius:'25px' if prod.f_image.attached?%>
      </div>

      <div style="display:flex;justify-content:center;height:25px; overflow: hidden; ">
        <b style="color:rgb(85, 77, 77); font-family: 'Times New Roman', Times, serif;"><%= prod.title %></b>
      </div>


      <!-- <-- show Catageroy product Price & Cart-->


      <div style="height:25px; display:flex; margin-left:5px; flex-direction:row; justify-content:space-between;">
        <p style="margin-top:15px;margin-left:10px;"><b>Price</b> <%= prod.price%></p>
        <div>
          <%= link_to "Add to Cart", addcart_path(prod.id), class:"btn btn-primary py-1", style:"border-radius:0 0 10px 0" %>
        </div>

      </div>
    </div>
  </a>
  <%end%>
</div>


<%
=end
%>

app/views/admin/catageroys/new.html.erb
<h1>New catageroy</h1>

<%= render "form", catageroy: @catageroy, url: admin_catageroys_path %>

<br>

<div>
  <%= link_to "Back to catageroys", admin_catageroys_path %>
  <div>
    <% @cat = Catageroy.all%>
    <% @cat.each do |cl|%>
      <div style="border:2px solid; border-radius:10px; width:300px; display:flex;justify-content:space-around">
      <a href="/admin/catageroys/<%= cl.id%>/edit"><%= cl.name %> </a>
      <%= link_to 'delete', admin_catageroy_path(cl.id), data: { turbo_method: :delete } %>
      </div>
    <%end%>
  </div>
</div>

app/views/admin/catageroys/show.html.erb
<!-- <-- Header-->
<div style="display:flex; justify-content:space-between;background-color:black">
  <div>
    <p style="color: green"><%= notice %></p>
    <a href="/catageroys" style="text-decoration: none;color:white">
      <h1>MastShop</h1>
    </a>
    <p style="margin-top:-15px;margin-left:10px; font-size:14px;color:pink">Comfortable Life Style</p>
  </div>

  <div>
    <div>
      <a href="/catageroys/<%= @catageroy.id%>" style="text-decoration: none;color:gray">
        <h3><%= @catageroy.name%></h3>
      </a>
    </div>
    <div style="margin-top:-15px">
      <%= link_to "Back", catageroys_path %> <b style="color:yellow">|</b>
      <%= link_to "Edit", edit_catageroy_path(@catageroy) %>
    </div>
  </div>

  <div>
    <a href="/carts" style="color:white; font-size:15px">
    <div class="position-relative d-flex justify-content-center align-items-start">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" width="30" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
      </svg>
      <div class="position-absolute bottom-0 mb-1">
      <%= Cart.count%>
      </div>
    </div>
  </a>
    <a href="/products/new/?cid=<%= @catageroy.id%>" style="text-decoration: none;margin-right:20px; color:gray">
      <h7> <b>+</b> Product</h7>
    </a>
    
  </div>
</div>

<%# <%= render @catageroy %>






<!-- <-- show Catageroy product-->

<div style="display:flex; flex-wrap:wrap; justify-content:center; ">

  <% @catageroy.products.each do |prod|%>
  <a href="/products/<%= prod.id%>" style="text-decoration: none;">
    <div
      style="display:flex; flex-direction:column; width:300px; height:300px; margin:30px; border-radius: 10px;background-color: white;">


      <!-- <-- show Catageroy product Image-->


      <div >
        <%= image_tag prod.f_image, height:'240px', width:'300px' ,border_radius:'25px' if prod.f_image.attached?%>
      </div>


      <!-- <-- show Catageroy product Title-->



      <div style="display:flex;justify-content:center;height:25px; overflow: hidden; ">
        <b style="color:rgb(85, 77, 77); font-family: 'Times New Roman', Times, serif;"><%= prod.title %></b>
      </div>


      <!-- <-- show Catageroy product Price & Cart-->


      <div style="height:25px; display:flex; margin-left:5px; flex-direction:row; justify-content:space-between;">
        <p style="margin-top:15px;margin-left:10px;"><b>Price</b> <%= prod.price%></p>
        <div><%= link_to "Add to Cart", addcart_path(prod.id), class:"btn btn-primary py-1", style:"border-radius:0 0 10px 0" %></div>

      </div>
    </div>
  </a>
  <%end%>

</div>





















<br><br>
<br><br>
<br><br>
<div>
  <%= link_to "Edit pthis catageroy", edit_catageroy_path(@catageroy) %> |
  <%= link_to "Back to catageroys", catageroys_path %>

  <%= button_to "Destroy this catageroy", @catageroy, method: :delete, class:'btn btn-outline-danger m-2' %>
</div>