config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :books
    end
  end
  devise_for :users
  root "catageroys#index"
  resources :products
  resources :catageroys
  resources :carts
  get 'carts/sub/:id', to: 'carts#sub', as: 'sub'
  get 'products/cart/:id', to: 'products#cart', as: 'addcart'
  # get 'carts/show', to: 'cart#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :admin do
    resources :products
    resources :catageroys
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :Catageroy
  has_one_attached :f_image
  has_many :carts,  foreign_key: "pid", dependent: :destroy
  validates :title, presence: true
  validates :qty, presence: true
  validates :des, presence: true

    



end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: %i[ show edit update destroy cart]
  before_action :check, only: %i[ show edit new update destroy cart ]
  # GET /products or /products.json
  def index
    @products = Product.all
  end
  # GET /products/1 or /products/1.json
  def show
  end
  # GET /products/new
  def new
    puts "Hello"
    @product = Product.new()
  end
  # GET /products/1/edit
  def edit
  end
  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_catageroys_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_catageroys_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to catageroys_path(@product.Catageroy_id), notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end






   def cart
       
     # redirect_to catageroy_path(@product.Catageroy_id)
       if Cart.create(:user=>current_user.email, :cid=>@product.Catageroy_id, :pid=>@product.id, :aqty=>@product.qty, :quantity=>1,:title=>@product.title, :price=>@product.price)
       respond_to do |format|
         format.html { redirect_to catageroy_path(@product.Catageroy_id), notice: "Product was successfully Add to Cart." }
         format.json { head :no_content }
       end
     end
   end








  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :des, :qty, :Catageroy_id, :price, :f_image)
    end



    def check
      if current_user && current_user.role == "admin"
        puts "Admin :"
        puts current_user.role
      else
        puts "Admin not Exist"
        redirect_to new_user_session_path
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy cart]
  before_action :authenticate_user!, only: %i[ cart ]
  # GET /products or /products.json
  def index
    @products = Product.all
  end
  # GET /products/1 or /products/1.json
  def show
  end
  # GET /products/new
  # def new
  #   @product = Product.new({:Catageroy_id=>params[:cid]})
  # end
  # GET /products/1/edit
  def edit
  end
  # POST /products or /products.json
  # def create
  #   @product = Product.new(product_params)

  #   respond_to do |format|
  #     if @product.save
  #       format.html { redirect_to admin_catageroys_path, notice: "Product was successfully created." }
  #       format.json { render :show, status: :created, location: @product }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admim_catageroys_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to catageroys_path(@product.Catageroy_id), notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end






   def cart
       
     # redirect_to catageroy_path(@product.Catageroy_id)
       if Cart.create(:user=>current_user.email, :cid=>@product.Catageroy_id, :pid=>@product.id, :aqty=>@product.qty, :quantity=>1,:title=>@product.title, :price=>@product.price)
       respond_to do |format|
         format.html { redirect_to catageroy_path(@product.Catageroy_id), notice: "Product was successfully Add to Cart." }
         format.json { head :no_content }
       end
     end
   end








  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :des, :qty, :Catageroy_id, :price, :f_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for product, url:url do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title%>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :des %>
    <%= form.text_field :des %>
  </div>

  <div>
    <%= form.label :qty %>
    <%= form.number_field :qty %>
  </div>

  <div>
    <%= form.label :Price %>
    <%= form.number_field :price %>
  </div>

  <div>
  <%= form.select :Catageroy_id, Catageroy.all.map{|e| [ e.name, e.id]} %>
   
  </div>

  <div>
    <%= form.file_field :f_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
 <div style="display:flex; justify-content:space-around">
      <div style="width:50%; height:500px;border:1px solid">
          <p style="border:1px solid"><%= image_tag product.f_image,height:'500px', width:'100%' %></p>
      </div>

      <div style="width:40%">
            <br><br>
            <h3 style="font-family:calibari">
              <%= product.title %>
            </h3>
         <div style="margin-top:-10px; display:flex;">
            <p style="color:gray;font-family:calibari">Price <%= product.price %></p>
            <p style="color:gray;margin-left:30px;font-family:calibari">
             Stock <%= product.qty %>
            </p>
        </div>


        <br><br><br>
       <%= link_to 'Add To Cart', addcart_path(product.Catageroy_id), class:"btn btn-primary "%>
          <br><br><br>
        <p>
          <h2 style="font-family:Arial">Description </h2>
          <p style="font-family:callibari"><%= product.des %></p>
        </p>
     </div>

  </div>
</div>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product, url:admin_product_path(@product) %>

<br>

<div>
  <%= link_to "Back to products", admin_catageroys_path %>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>
<%= render "form", product: @product, url:admin_products_path  %>

<br>

<div>
  <%= link_to "Back", admin_catageroys_path %>
</div>

app/views/admin/products/show.html.erb
<div style="display:flex; justify-content:space-between; background-color:black">
   <div>
     <p style="color: green"><%= notice %></p>
      <a href="/catageroys" style="text-decoration: none;color:white"><h1>MastShop</h1></a>
      <p style="margin-top:-12px;margin-left:10px; font-size:14px;color:pink">Comfortable Life Style</p>
   </div>
   <div style="margin-right:40px">
      <%= button_to "Remove Product", @product, method: :delete %>
      <%= link_to "Back", catageroy_path(@product.Catageroy_id)%> <b style="color:yellow"> |</b>
      <%= link_to "Edit Product", edit_product_path(@product) %>
   </div>
</div>
<hr>

<%= render @product %>